[programs.devnet]
metaverse_staking = "EXZJ3cCRD8dxmTYPxY4nWEWjGiwiW1U9yz2jzJzngnLg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/artemiyartamonov/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*"
